apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-serv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: posts.blog.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: post-clusterip-srv
                port:
                  number: 4000
    - host: comments.blog.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
    - host: query.blog.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 4002
    - host: blog.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
