apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sostene/ticketing-auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-jwt-secret
                  key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: auth-serv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
